import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local';
import { Toaster } from "sonner";
import "./globals.css";


const vcrMono = localFont({
  src: '../assets/fonts/VCR_OSD_MONO_1.001.ttf', // Check your exact filename inside the folder
  variable: '--font-vcr', // The CSS variable Tailwind will use
  display: 'swap',
});

const lemonMilk = localFont({
  src: [

    {
      path: '../assets/fonts/lemon_milk/LEMONMILK-Light.otf',
      weight: '300',
      style: 'normal',

    }
  ],
  variable: '--font-lemon', // The CSS variable Tailwind will use
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${lemonMilk.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
